services:
  db:
    container_name: bottari-mysql
    image: ${TEST_DATABASE_IMAGE}
    ports:
      - "3306:3306"
    environment:
      # 아래 값들은 .env 파일(또는 GHA env)에서 주입됨
      MYSQL_DATABASE: ${TEST_DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${TEST_DATABASE_PASSWORD}
    # 문자열 형태로 주어야 환경변수 치환이 안전하게 동작
    command: --ngram_token_size=${TEST_NGRAM_TOKEN_SIZE}

    # 헬스체크로 "mysql 올라옴"을 보장 (GHA 루프 대체 가능)
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p${TEST_DATABASE_PASSWORD} --silent"]
      interval: 5s
      timeout: 2s
      retries: 36
      start_period: 10s