spring:
  application:
    name: bottari
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    master:
      hikari:
        pool-name: HIKARI-MASTER
        jdbc-url: ${WRITE_DATABASE_URL}
        username: ${WRITE_DATABASE_USERNAME}
        password: ${WRITE_DATABASE_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    replica:
      hikari:
        pool-name: HIKARI-REPLICA
        jdbc-url: ${READ_DATABASE_URL}
        username: ${READ_DATABASE_USERNAME}
        password: ${READ_DATABASE_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never
management:
  metrics:
    enable:
      all: false
      app.health.status: true
  cloudwatch:
    metrics:
      export:
        enabled: true
        step: 1m
        namespace: EC2/bottari-prod-api
firebase:
  service:
    key-path: ${FIREBASE_SERVICE_ACCOUNT_JSON}
