spring:
  application:
    name: bottari
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
    enable:
      all: false
      jvm.memory.used: true
      jvm.memory.max: true
      jvm.gc.pause: true
      http.server.requests: true
      jvm.threads.states: true
      jvm.threads.live: true
      hikaricp.connections.active: true
      hikaricp.connections.idle: true
      hikaricp.connections.pending: true
      hikaricp.connections.max: true
      app.health.status: true
  cloudwatch:
    metrics:
      export:
        enabled: true
        step: 1m
        namespace: EC2/bottari-dev-api
firebase:
  service:
    key-path: ${FIREBASE_SERVICE_ACCOUNT_JSON}
