name: deploy-dev-server

on:
  push:
    branches:
      - be/develop

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/bottari-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    name: Build & Push to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # GHCR push를 위해 필요

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build Jar
        working-directory: ./backend/bottari
        run: ./gradlew clean build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image (ARM64)
        working-directory: ./backend/bottari
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t $IMAGE_NAME:$IMAGE_TAG \
            -t $IMAGE_NAME:latest \
            --push .

  deploy:
    name: Deploy to Dev Server
    needs: build
    runs-on: [self-hosted, bottari-dev]

    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest image from GHCR
        run: |
          docker pull $IMAGE_NAME:$IMAGE_TAG

      - name: Deploy using Docker Compose
        working-directory: /home/ubuntu
        run: |
          IMAGE_NAME=$IMAGE_NAME \
          IMAGE_TAG=$IMAGE_TAG \
          FIREBASE_SERVICE_ACCOUNT_JSON='${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}' \
          docker compose -f docker-compose.dev.yml up -d --force-recreate
